$attachment = Job::findOrFail($id);
        $attachment->job_title = $request->input('attachment_title');
        $attachment->job_description = $request->input('task_description');
        $attachment->slots_needed = $request->input('attachment_slots');
        $attachment->job_category =  implode(',', (array) $request->get('category'));
        $attachment->course =  implode(',', (array) $request->get('course'));
        $attachment->appreciation_token = $request->input('appreciation_token');
        $attachment->attachment_start = $request->input('attachment_start');
        $attachment->attachment_end = $request->input('attachment_end');
        $attachment->gender = $request->input('gender');
        $attachment->qualification = $request->input('requirements_needed');
        $attachment->additional_information = $request->input('additional_information');
        $attachment->attachment_status = "Active";
        // $attachment->company_user_id = auth()->user()->id;
        $attachment->save();
